### ISSUE TITLE
Prefer 2.0.0 layout over the 3.0.0 layout

### ISSUE THREAD

**Issue by xyzzy-xyzzy** [MailHops/mailhops-plugin#10]
Could you please add a preference/setting to display the mailhops info as part of the mail header display like it was in 2.0.0?  I prefer the 2.0.0 layout to this 3.0.0 layout boldly breaking up the header from the mail content with a separate dark blue bar.

Note, I'd be happy even if you kept the new bar info/layout but just displayed it as part of the mail header info like 2.0.0 did.

**Comment by avantassel** [comment]
The mail header space is limited and why it was moved in 3.0.  I am adding options for you to be able to customize the bar, you'll be able to change the bar color, font color and font size.

**Comment by avantassel** [comment]
The layout has definitely changed since then.  closing since not really relevant anymore.
