### ISSUE TITLE
Need more strings to be translatable

### ISSUE THREAD

**Issue by ldmpub** [MailHops/mailhops-plugin#14]
Hi,

This plugin is great thanks ! But is not fully translatable yet. For instance:
- view map
- unsubscribe
- MailHops Map
- Map templates
- all preferences dialog
- ...

Is it possible to allow translation of these strings in any language or did I missed some existing files I can already translate?

Best regards,

**Comment by avantassel** [comment]
it is possible on everything except the popup map.

**Comment by ldmpub** [comment]
Thanks for this quick answer.

Can you point me the files containing strings to translate ? yet I only know folder "chrome/locale/xx/" containing 2 files with 16 strings.

Regards,

**Comment by avantassel** [comment]
The bar now has language support on all text, the preferences will be next, basically it's creating a variable in the 2 locale strings files for each language.  Then using that variable in the preferences.xul file.

**Comment by ldmpub** [comment]
Thanks. I have reviewed and made a pull request for all available strings for french.

My priority for translation will be:
1. bar
2. map dialog
3. preferences dialog.

Regards,

**Comment by avantassel** [comment]
closing this since the translation framework has changed.

**Comment by ldmpub** [comment]
Hi @avantassel,

Can you please give me more details on how to contribute to a translation please?

**Comment by ldmpub** [comment]
It seems like Translation files have been removed from Master 🤨.

Please find below "old translation framework" files,
![image](https://github.com/user-attachments/assets/5430cccd-d08a-44a1-a4d3-15d9796dadcb)

**Where can I found the strings for a particular language in the "new framework"?**

Thanks in advance,
