### ISSUE TITLE
Default Language setting has no effect

### ISSUE THREAD

**Issue by sicherist** [MailHops/mailhops-plugin#20]
Hi,

thank you for creating MailHops Add on! The localisation is yet a bit bumpy. I assume you used automatic translation, which led to reminding me of how refreshing beer is ;)

I would propose to delete all localisations that were created automatically. Most users will be better suited with proper english labels instead of incorrect translations.

However I would be happy to translate other parts of the UI  as well, like in the preferences dialog, if possible.

One thing I noticed was that I could not change the language of the plugin via the 'default language' setting in the 'default' tab in Mailhops preferences. No matter what language I selected, everything stayed in german language.

Best regards!

**Comment by ldmpub** [comment]
Hi,

[OFF TOPIC ON]
Welcome, I have exactly the same experience with the french "automated" translation which also propose me 1 string related to "bier".
I will also be happy to translate other parts of the UI as well.
[OFF TOPIC OFF]

On my side french translation is used by the addon.

Regards,

**Comment by sicherist** [comment]
Thanks for your reply. Could you check if you can change the language to english or german? This setting has no effect for me.

>1 string related to "bier".

I especially liked the button 'erfrischen' (refresh). 'Erfrischen' isn't used in german in IT-context but only for things like refreshing drinks, cool showers, etc. ;-)

**Comment by ldmpub** [comment]
I'm sorry I can not perform any test because I'm far away from my Thunderbird computer until end of week.

1 string related to "bier": in french it was the word 'hop' which has been translated to 'houblon' which is the main cereal used to produce a bier ;-).

**Comment by avantassel** [comment]
Hi, thanks for the feedback.  The language gets set with the downloaded Thunderbird version.  The language option in the MailHops preferences is for the API response for location.  I started adding locales for preferences and are in locale/prefs.dtd.  I did just use google translate but can set the default to english and let native speakers update that.  Thanks again.

**Comment by avantassel** [comment]
Thank you
