### ISSUE TITLE
UI: no enough difference between pushed and unpushed state for buttons

### ISSUE THREAD

**Issue by ldmpub** [MailHops/mailhops-plugin#26]
Example on the "route [EN] / trajet [FR]" button:

Unpushed / inactive Pop-up

![unpushed](https://user-images.githubusercontent.com/1452146/44615808-5eb51100-a843-11e8-906a-415b564556ae.jpg)

Pushed / Pop-up enabled
![button pushed](https://user-images.githubusercontent.com/1452146/44615813-75f3fe80-a843-11e8-84ad-b190e020a5d4.jpg)

Issues:
- User may have pressed button by error and do not understand how to remove the popup to read top of message which is actually hidden
- when pressed, the button keeps this state when opening other mails => not sure if it's the wanted behaviour (note: personnaly I don't mind because now I have learned to press / unpress buttons 👎 ).

Running:
- Thunderbird 52.9.1 
- Extension 3.1.8
- Windows 10

**Comment by avantassel** [comment]
This is default now.
