### ISSUE TITLE
MailHops is incompatible with Thunderbird 68.1.0

### ISSUE THREAD

**Issue by alset333** [MailHops/mailhops-plugin#27]
Thunderbird has disabled the add-on with the message "MailHops is incompatible with Thunderbird 68.1.0".

**Comment by Hillside502** [comment]
Come on dev, please reply with a timescale.

**Comment by Hillside502** [comment]
Last chance before I cancel my 5 USD a month subscription.

Silence equals dumb insolence!

**Comment by Hillside502** [comment]
Subscription cancelled, account closed, unstarred

**Comment by avantassel** [comment]
This was updated April 2019 c826f5eab4f1778bd8daf3e7f05bd667d81c9732
