### ISSUE TITLE
Email in vertical layout not properly displayed

### ISSUE THREAD

**Issue by slizzered** [MailHops/mailhops-plugin#3]
**[this issue is a duplicate of https://github.com/avantassel/mailhops-thunderbird/issues/2 from the old repository]**

When using the vertical layout in Thunderbird (Menu -> Preferences -> Layout -> Vertical View), some mails are cut off, if the width of the "Mail" column is reduced too far. This seems to be related to some layout problem with the "Route" row that is introduced by the plugin. The column is no longer capable of resizing the window correctly. Instead, it is forced to some minimum width that seems to depend on the Route row (the cutoff gets worse if the string for the route gets longer).
### everything OK, when the column is large enough:

![wide_hops](https://cloud.githubusercontent.com/assets/903310/7554263/bc81dd72-f720-11e4-8233-d87dd613fff4.png)
### Problem arises when column gets too small

The whole window is moved to the right, and everything gets cut off. Buttons are cut in half, long lines of text simply disappear instead of wrapping. The following image is **not** cut by image editing, but displays the whole Thunderbird window:
![tight_hops](https://cloud.githubusercontent.com/assets/903310/7554266/df90c9e0-f720-11e4-87a8-621a4d24e796.png)
### When disabling the plugin it works as expected

The buttons are aligned better, and, most importantly, the text is wrapped around as it should:
![tight_default](https://cloud.githubusercontent.com/assets/903310/7554267/0905a0fc-f721-11e4-8f2e-135d62f3b423.png)

**Comment by avantassel** [comment]
This has been resolved with the new layout design in version 3.0.0
