### ISSUE TITLE
SPF Softfail Icon is missing

### ISSUE THREAD

**Issue by Jogile1** [MailHops/mailhops-plugin#30]
In Thunderbird 102.7.0 (64-Bit) on Windows the SPF Icon load failed (s. Screenshot)
![31-01-_2023_10-44-15](https://user-images.githubusercontent.com/71124906/215725590-ba16ac43-2633-4fed-a916-7f287e09f78f.png)

**Comment by Ionic** [comment]
Will be fixed by either #36 or #38, depending on whether this was detected through the `Received-SPF` or `Authentication-Header` header.

**Comment by avantassel** [comment]
This is fixed with 151c08bb88f50cbae3d6b3f2623ee3475f8e9c01
