### ISSUE TITLE
DKIM and country filter options

### ISSUE THREAD

**Issue by thwaller** [MailHops/mailhops-plugin#5]
On Thunderbird, the SPF pass indicator is appearing, but not the DKIM. It is not showing at all, pass or fail. Also, in the options, all of the country checkboxes are grey, cannot check or uncheck any of them. Is there anything that needs to be done on Thunderbird to access these features? I installed from the Mozilla link.

**Comment by avantassel** [comment]
Currently MailHops only uses the `Authentication-Results` header for the DKIM result.  Using the `DKIM-Signature` header and verify the signature is something that should be added.  Currently the Filters are only available with an API key.

**Comment by avantassel** [comment]
these options are there now
