### ISSUE TITLE
Bug in header parsing

### ISSUE THREAD

**Issue by ccpp** [MailHops/mailhops-plugin#9]
All my mail seems to have a hop somewhere in Palo Alto, because the SMTP server version/ID (15.1.225.42) is parsed as if it was an IP address.  IP Addresses should only be read from the `from` clause, not the `id` clause, even if it looks like a valid IPv4 address :)

    Received: from mx3.**** (*.*.*.*) by
     mx3.**** (*.*.*.*) with Microsoft SMTP Server (TLS) id
     15.1.225.42 via Mailbox Transport; Thu, 22 Dec 2016 14:46:26 +0100
    Received: from mail.**** (*.*.*.*) by mx3.****
     (*.*.*.*) with Microsoft SMTP Server id 15.1.225.42; Thu, 22 Dec 2016
     14:46:26 +0100

This might also touch issue #6.

The affected version numbers are listed at https://social.technet.microsoft.com/wiki/contents/articles/15776.exchange-server-2013-and-2016-build-numbers-with-cumulative-updates.aspx and https://eightwone.com/references/versions-builds-dates/

**Comment by avantassel** [comment]
Thanks, I'll be working on a fix and will be in the next release, i'll close this when it's up.
